apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user }}
  DB_PASSWORD: {{ .Values.db.passwd }}
  DB_NAME: {{ .Values.db.dbname }}