apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-pod-0
  labels:
    prj: ws
spec:
  containers:
    - name: webserver-1
      image: nginx:alpine
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - webserver
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-pod-1
  labels:
    prj: ws
spec:
  containers:
    - name: webserver-1
      image: nginx:alpine
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: role
              operator: In
              values:
              - webserver