apiVersion: v1
kind: Service
metadata:
  name: hello-minikube-service
spec:
  selector:
    app: hello-minikube   
  ports:
    - protocol: TCP
      port: 3005  
      targetPort: 3000   
      nodePort: 30000   
  type: NodePort   
