apiVersion: v1
kind: Pod
metadata:
  name: multi-cont-pod
  labels:
    prj: example
spec:
  containers:
    - name: app-01
      image: debian
      command: ["sleep", "infinity"]
    - name: db-01
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: root
      ports:
        - containerPort: 5432