apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: downhill_diary
  MYSQL_USER: downhill_user
  MYSQL_PASSWORD: downhill_pass
