apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.db.dbName | quote }}
  MYSQL_USER: {{ .Values.db.dbUser | quote }}
  MYSQL_PASSWORD: {{ .Values.db.userPass | quote }}
